script: main_forget
dataset: cifar10

model_path: ./checkpoints/cifar10/resnet18/2/0model_SA_best.pth.tar
retrain_path: ./logs/cifar10/random_50percent/baselines/Retrain/run_01/retraincheckpoint.pth.tar

num_indexes_to_replace: 22500

save_dir: ./logs/cifar10/random_50percent/baselines/FT/run_02

unlearn: FT
unlearn_epochs: 10
unlearn_lr: 1e-2

wandb_entity: rasa_research
wandb_group: FT
wandb_name: FT-lr_1e-2-run_02
