script: main_forget
dataset: cifar10

model_path: ./checkpoints/cifar10/resnet18/2/0model_SA_best.pth.tar
retrain_path: ./logs/cifar10/random_50percent/baselines/Retrain/run_01/retraincheckpoint.pth.tar

num_indexes_to_replace: 22500
alpha: 1

save_dir: ./logs/cifar10/random_50percent/baselines/IU/run_01

unlearn: wfisher
unlearn_epochs: 10
unlearn_lr: 1e-3

wandb_entity: rasa_research
wandb_group: IU
wandb_name: IU-lr_1e-3-alpha_1-run_01
