script: main_forget
dataset: cifar10

model_path: ./checkpoints/cifar10/resnet18/2/0model_SA_best.pth.tar
retrain_path: ./logs/cifar10/random_50percent/baselines/Retrain/run_01/retraincheckpoint.pth.tar

num_indexes_to_replace: 22500

save_dir: ./logs/cifar10/random_50percent/mojd/MO-CE+UniDist-MGDA-AdamW-lr_7.5e-5/run_04

unlearn: MO_JD_CE_UniDist
mo_aggregator: mgda
unlearn_epochs: 5
unlearn_lr: 7.5e-5
optimizer: adamw
scheduler: none

wandb_entity: rasa_research
wandb_project: mu-classification
wandb_group: MO-CE+UniDist-MGDA-AdamW
wandb_name: MO-CE+UniDist-MGDA-AdamW-lr_7.5e-5
