script: main_forget
dataset: cifar10

model_path: ./checkpoints/cifar10/resnet18/2/0model_SA_best.pth.tar
retrain_path: ./logs/cifar10/random_10percent/baselines/Retrain/run_01/retraincheckpoint.pth.tar

num_indexes_to_replace: 4500

save_dir: ./logs/cifar10/random_10percent/mojd/MO-CE+HeldDist-UPGrad-SGD-lr_2.5e-3/run_01

unlearn: MO_JD_CE_KL
mo_aggregator: upgrad
unlearn_epochs: 5
unlearn_lr: 2.5e-3
optimizer: sgd
scheduler: none

wandb_entity: rasa_research
wandb_project: mu-classification
wandb_group: MO-CE+HeldDist-UPGrad-SGD
wandb_name: MO-CE+HeldDist-UPGrad-SGD-lr_2.5e-3
